# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 625252f8c9feb129c0418176e5f2f445238e2426d9afab41ba92816056b34917fdceb7b31e62f3005d1f39c6816198dd1b1ff6999d99ff9667c22bd4199e6961

test:
  secret_key_base: 0e9c8ef42169a0a955a407c96432cf38906de006e54944feedd3250e97721c6b2d96bd3c92abdceaedd2b50c7f06f345f76ac0c80753d0b1f88bbd5a74415d00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
